docs: add example for piping anonymous fn
blackode/elixir-tips pull request #47
Opened 2022-03-04 09:20 UTC by rodesousa

Signed-off-by: rodesousa <dessroberto@gmail.com>

2022-03-05 12:56 UTC, blackode requested changes
Mention the elixir version as `then` macro is available from `1.12.0`.

2022-03-05 12:56 UTC, blackode commented on README.md
> +Or use `Kernel.then/2` function
```suggestion
Or use `Kernel.then/2` function since 1.12.0
```

2022-03-07 16:56 UTC, rodesousa commented on README.md
> +Or use `Kernel.then/2` function
done !

2022-03-08 07:37 UTC, merged

2022-03-08 07:43 UTC, blackode commented
@all-contributors add @rodesousa for code